name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@5f19ec79cedfadb78ab837f95b87734d0003c899 # pin@v1.173.0
        with:
          bundler-cache: true

      - name: rubocop
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
