name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.1.2', '3.1.4', '3.2.2', '3.2.3', '3.3.0', '3.3.1' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@0cde4689ba33c09f1b890c1725572ad96751a3fc # pin@v1.178.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test -d -k
